#!/bin/bash
# ==============================================================================
# Script Name: epas-rebuild-standby.sh
# Description: Automated Standby Provisioning & Cloning for EDB Postgres 
#              Advanced Server (EPAS) 15. Utilizes authorized sudo escalations
#              to run entirely under the 'enterprisedb' service account.
# ==============================================================================

set -euo pipefail

# --- Configuration ---
SERVICE_NAME="edb-as-15"
DATA_DIR="/var/lib/edb/as15/data"
BACKUP_DIR_PREFIX="/var/lib/edb/as15/data_bak"
SYSTEM_USER="enterprisedb"
SYSTEM_GROUP="enterprisedb"

PRIMARY_HOST="Primary.com"
PRIMARY_PORT="5444"
REP_USER="repuser"

# --- Validation: Ensure script runs as enterprisedb ---
CURRENT_USER=$(whoami)
if [[ "${CURRENT_USER}" != "${SYSTEM_USER}" ]]; then
    echo "ERROR: This script must be executed as the '${SYSTEM_USER}' user." >&2
    exit 1
fi

echo "=== [1/4] Stopping EPAS Service & Preparing Directories ==="

# 1. Stop EPAS service via sudo whitelist
echo "Stopping ${SERVICE_NAME}..."
sudo /bin/systemctl stop "${SERVICE_NAME}"

# 2. Archive existing data directory if it exists
if [[ -d "${DATA_DIR}" ]]; then
    BACKUP_PATH="${BACKUP_DIR_PREFIX}_$(date +%F_%H%M%S)"
    echo "Archiving existing data directory to: ${BACKUP_PATH}"
    sudo /bin/mv "${DATA_DIR}" "${BACKUP_PATH}"
fi

# 3. Recreate and permission data directory via sudo whitelist
echo "Reinitializing clean data directory structures..."
sudo /bin/mkdir -p "${DATA_DIR}"
sudo /bin/chown $SYSTEM_USER:$SYSTEM_GROUP "${DATA_DIR}"
sudo /bin/chmod 700 "${DATA_DIR}"


echo "=== [2/4] Executing pg_basebackup from Primary ==="

# 4. Run pg_basebackup natively as enterprisedb
pg_basebackup \
    -h "${PRIMARY_HOST}" \
    -p "${PRIMARY_PORT}" \
    -U "${REP_USER}" \
    -D "${DATA_DIR}" \
    -Fp -Xs -P -R -v


echo "=== [3/4] Verifying Standby Configuration ==="

# 5. Verify replica catch-up file exists
if [[ ! -f "${DATA_DIR}/standby.signal" ]]; then
    echo "ERROR: standby.signal was not generated by pg_basebackup." >&2
    exit 1
fi
echo "Success: standby.signal is present."


echo "=== [4/4] Starting EPAS Standby Service ==="

# 6. Start service via sudo whitelist
sudo /bin/systemctl start "${SERVICE_NAME}"

# 7. Quick status check
sudo /usr/bin/systemctl status "${SERVICE_NAME}" --no-pager


echo "=========================================================================="
echo " Standby Provisioning Complete. Run these metrics to verify health:"
echo "=========================================================================="
cat << EOF

On the PRIMARY Node:
--------------------------------------------------------------------------
SELECT 
    pid, usename, application_name, client_addr, state, sync_state,
    sent_lsn, replay_lsn,
    pg_size_pretty(pg_wal_lsn_diff(sent_lsn, replay_lsn)) AS replication_lag
FROM pg_stat_replication;

On this STANDBY Node:
--------------------------------------------------------------------------
SELECT 
    pg_is_in_recovery() AS in_recovery,
    pg_last_wal_receive_lsn() AS last_received,
    pg_last_wal_replay_lsn() AS last_replayed,
    pg_last_xact_replay_timestamp() AS last_replay_time;

EOF