#!/usr/bin/env bash
#
# setup_hugepages_root.sh - Phase 1: OS Kernel Tuning for EPAS
# Must be executed as root.
#

set -euo pipefail

EPAS_USER="enterprisedb"
SERVICE_NAME="edb-as-17"
ENV_FILE=""

log()  { echo -e "[INFO] $*"; }
warn() { echo -e "[WARN] $*" >&2; }
err()  { echo -e "[ERROR] $*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --env)
            ENV_FILE="$2"
            shift 2
            ;;
        --user)
            EPAS_USER="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [--env /path/to/deploy.env] [--user enterprisedb]"
            exit 0
            ;;
        *)
            err "Unknown option: $1"
            ;;
    esac
done

# Load deploy.env if provided
if [[ -n "$ENV_FILE" ]]; then
    [[ -f "$ENV_FILE" ]] || err "Environment file not found: $ENV_FILE"
    set -o allexport
    source "$ENV_FILE"
    set +o allexport
    EPAS_USER="${SYSTEM_USER:-$EPAS_USER}"
    SERVICE_NAME="${SERVICE_NAME:-edb-as-17}"
fi

[[ "$EUID" -eq 0 ]] || err "This script must be run as root."

log "===================================================="
log " Starting EPAS Phase 1 OS Kernel Optimization"
log "===================================================="
log "Target User: $EPAS_USER | Service: $SERVICE_NAME"

# 1. Calculate Pages
log "[1/5] Calculating HugePages from running EPAS shared memory..."

HP_SIZE_KB=$(awk '/^Hugepagesize/ {print $2}' /proc/meminfo)
[[ -n "$HP_SIZE_KB" && "$HP_SIZE_KB" -gt 0 ]] || err "Cannot read Hugepagesize from /proc/meminfo."

SHARED_BYTES=$(ipcs -m | awk -v u="$EPAS_USER" '$3 == u {sum+=$5} END {print sum+0}')
[[ "$SHARED_BYTES" -gt 0 ]] || err "No active shared memory for user '$EPAS_USER'. Is EPAS running?"

SHARED_KB=$(( SHARED_BYTES / 1024 ))
RAW_PAGES=$(( (SHARED_KB + HP_SIZE_KB - 1) / HP_SIZE_KB ))
TARGET_PAGES=$(( RAW_PAGES + (RAW_PAGES / 10) + 20 ))

EPAS_GID=$(id -g "$EPAS_USER" 2>/dev/null) || err "OS user '$EPAS_USER' does not exist."
log "      Shared Memory: ${SHARED_KB} KB | Page Size: ${HP_SIZE_KB} KB"
log "      Target Pages:  $TARGET_PAGES | EPAS GID: $EPAS_GID"

# 2. Kernel Parameters
SYSCTL_CONF="/etc/sysctl.d/99-${SERVICE_NAME}-hugepages.conf"
log "[2/5] Writing $SYSCTL_CONF..."
cat << EOF > "$SYSCTL_CONF"
# Auto-generated by setup_hugepages_root.sh
vm.nr_hugepages = $TARGET_PAGES
vm.hugetlb_shm_group = $EPAS_GID
EOF
sysctl -p "$SYSCTL_CONF" >/dev/null

# 3. Shell Limits
LIMITS_CONF="/etc/security/limits.d/99-${SERVICE_NAME}-memlock.conf"
log "[3/5] Writing $LIMITS_CONF..."
cat << EOF > "$LIMITS_CONF"
# Auto-generated by setup_hugepages_root.sh
$EPAS_USER soft memlock unlimited
$EPAS_USER hard memlock unlimited
EOF

# 4. Disable THP
log "[4/5] Disabling Transparent Huge Pages..."
if command -v tuned-adm &>/dev/null; then
    mkdir -p /etc/tuned/epas-no-thp
    cat << EOF > /etc/tuned/epas-no-thp/tuned.conf
[main]
include=throughput-performance
[vm]
transparent_hugepages=never
EOF
    tuned-adm profile epas-no-thp >/dev/null 2>&1 || warn "tuned-adm profile switch failed; using sysfs fallback."
fi

if [[ -f /sys/kernel/mm/transparent_hugepage/enabled ]]; then
    echo never > /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null || true
fi
if [[ -f /sys/kernel/mm/transparent_hugepage/defrag ]]; then
    echo never > /sys/kernel/mm/transparent_hugepage/defrag 2>/dev/null || true
fi

# 5. Verification Gate
log "[5/5] Verifying kernel allocation..."
sleep 1
ACTUAL_PAGES=$(awk '/^HugePages_Total/ {print $2}' /proc/meminfo)

if [[ "$ACTUAL_PAGES" -lt "$TARGET_PAGES" ]]; then
    warn "Allocated only $ACTUAL_PAGES / $TARGET_PAGES pages."
    warn "Memory is likely fragmented. REBOOT before enabling huge_pages='on' in EPAS."
    exit 2
else
    log "SUCCESS: $ACTUAL_PAGES HugePages allocated."
fi

log "===================================================="
log " OS Phase 1 Complete. Handoff to DBA."
log "===================================================="