#!/usr/bin/env bash
#
# setup_epas_kernel.sh - OS Kernel Tuning for EPAS (HugePages + Overcommit + Writeback)
# Must be executed as root.
#

set -euo pipefail

EPAS_USER="enterprisedb"
SERVICE_NAME="edb-as-17"
ENV_FILE=""

log()  { echo -e "[INFO] $*"; }
warn() { echo -e "[WARN] $*" >&2; }
err()  { echo -e "[ERROR] $*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --env)
            ENV_FILE="$2"
            shift 2
            ;;
        --user)
            EPAS_USER="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [--env /path/to/deploy.env] [--user enterprisedb]"
            exit 0
            ;;
        *)
            err "Unknown option: $1"
            ;;
    esac
done

# Load deploy.env if provided
if [[ -n "$ENV_FILE" ]]; then
    [[ -f "$ENV_FILE" ]] || err "Environment file not found: $ENV_FILE"
    set -o allexport
    source "$ENV_FILE"
    set +o allexport
    EPAS_USER="${SYSTEM_USER:-$EPAS_USER}"
    SERVICE_NAME="${SERVICE_NAME:-edb-as-17}"
fi

[[ "$EUID" -eq 0 ]] || err "This script must be run as root."

log "===================================================="
log " Starting EPAS OS Kernel Optimization"
log "===================================================="
log "Target User: $EPAS_USER | Service: $SERVICE_NAME"

# ------------------------------------------------------------------
# 1. System Info
# ------------------------------------------------------------------
TOTAL_KB=$(awk '/^MemTotal/ {print $2}' /proc/meminfo)
HP_SIZE_KB=$(awk '/^Hugepagesize/ {print $2}' /proc/meminfo)
[[ -n "$HP_SIZE_KB" && "$HP_SIZE_KB" -gt 0 ]] || err "Cannot read Hugepagesize from /proc/meminfo."

EPAS_GID=$(id -g "$EPAS_USER" 2>/dev/null) || err "OS user '$EPAS_USER' does not exist."

# ------------------------------------------------------------------
# 2. Calculate HugePages from running EPAS shared memory
# ------------------------------------------------------------------
log "[1/6] Calculating HugePages from running EPAS shared memory..."

SHARED_BYTES=$(ipcs -m | awk -v u="$EPAS_USER" '$3 == u {sum+=$5} END {print sum+0}')
if [[ "$SHARED_BYTES" -le 0 ]]; then
    warn "No active shared memory for user '$EPAS_USER'. Using fallback estimate."
    # Fallback: 25% of total RAM as shared_buffers proxy
    SHARED_KB=$(( TOTAL_KB / 4 ))
else
    SHARED_KB=$(( SHARED_BYTES / 1024 ))
fi

RAW_PAGES=$(( (SHARED_KB + HP_SIZE_KB - 1) / HP_SIZE_KB ))
TARGET_PAGES=$(( RAW_PAGES + (RAW_PAGES / 10) + 20 ))

log "      Total RAM:     ${TOTAL_KB} KB"
log "      Shared Memory: ${SHARED_KB} KB"
log "      Page Size:     ${HP_SIZE_KB} KB"
log "      Target Pages:  $TARGET_PAGES"

# ------------------------------------------------------------------
# 3. Calculate Overcommit Limit (kbytes)
# ------------------------------------------------------------------
log "[2/6] Calculating strict overcommit limit..."

HP_RESERVED_KB=$(( TARGET_PAGES * HP_SIZE_KB ))
AVAILABLE_KB=$(( TOTAL_KB - HP_RESERVED_KB ))
# 80% of non-HugePage RAM + fixed 2 GB buffer for sidecars
OVERCOMMIT_KB=$(( (AVAILABLE_KB * 80 / 100) + 2097152 ))

# Safety floor: never go below 1 GB
if [[ "$OVERCOMMIT_KB" -lt 1048576 ]]; then
    OVERCOMMIT_KB=1048576
    warn "Overcommit limit fell below 1 GB; clamped to 1 GB."
fi

log "      HugePages Reserved: ${HP_RESERVED_KB} KB"
log "      Available RAM:      ${AVAILABLE_KB} KB"
log "      Overcommit Limit:   ${OVERCOMMIT_KB} KB"

# ------------------------------------------------------------------
# 4. Write sysctl drop-in
# ------------------------------------------------------------------
SYSCTL_CONF="/etc/sysctl.d/99-${SERVICE_NAME}-kernel.conf"
log "[3/6] Writing $SYSCTL_CONF..."

cat << EOF > "$SYSCTL_CONF"
# Auto-generated by setup_epas_kernel.sh
# --- HugePages ---
vm.nr_hugepages = $TARGET_PAGES
vm.hugetlb_shm_group = $EPAS_GID

# --- Strict Overcommit ---
# Prevents OOM killer from targeting the postmaster.
# Limit = 80% of (RAM - HugePages) + 2 GB fixed buffer.
vm.overcommit_memory = 2
vm.overcommit_kbytes = $OVERCOMMIT_KB

# --- Dirty Page Writeback (low-latency tuning) ---
# Flush smaller batches more often to avoid latency spikes.
vm.dirty_background_ratio = 5
vm.dirty_ratio = 10
vm.dirty_writeback_centisecs = 200
EOF

sysctl -p "$SYSCTL_CONF" >/dev/null

# ------------------------------------------------------------------
# 5. Shell Limits (memlock for HugePages)
# ------------------------------------------------------------------
LIMITS_CONF="/etc/security/limits.d/99-${SERVICE_NAME}-memlock.conf"
log "[4/6] Writing $LIMITS_CONF..."

cat << EOF > "$LIMITS_CONF"
# Auto-generated by setup_epas_kernel.sh
$EPAS_USER soft memlock unlimited
$EPAS_USER hard memlock unlimited
EOF

# ------------------------------------------------------------------
# 6. Disable Transparent Huge Pages
# ------------------------------------------------------------------
log "[5/6] Disabling Transparent Huge Pages..."

if command -v tuned-adm &>/dev/null; then
    mkdir -p /etc/tuned/epas-no-thp
    cat << EOF > /etc/tuned/epas-no-thp/tuned.conf
[main]
include=throughput-performance
[vm]
transparent_hugepages=never
EOF
    tuned-adm profile epas-no-thp >/dev/null 2>&1 || warn "tuned-adm profile switch failed; using sysfs fallback."
fi

if [[ -f /sys/kernel/mm/transparent_hugepage/enabled ]]; then
    echo never > /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null || true
fi
if [[ -f /sys/kernel/mm/transparent_hugepage/defrag ]]; then
    echo never > /sys/kernel/mm/transparent_hugepage/defrag 2>/dev/null || true
fi

# ------------------------------------------------------------------
# 7. Verification Gate
# ------------------------------------------------------------------
log "[6/6] Verifying kernel allocation..."
sleep 1

ACTUAL_PAGES=$(awk '/^HugePages_Total/ {print $2}' /proc/meminfo)
ACTUAL_OVERCOMMIT=$(awk '/^CommitLimit/ {print $2}' /proc/meminfo)

if [[ "$ACTUAL_PAGES" -lt "$TARGET_PAGES" ]]; then
    warn "Allocated only $ACTUAL_PAGES / $TARGET_PAGES HugePages."
    warn "Memory is likely fragmented. REBOOT before enabling huge_pages='on' in EPAS."
    HP_STATUS=1
else
    log "SUCCESS: $ACTUAL_PAGES HugePages allocated."
    HP_STATUS=0
fi

log "      CommitLimit: ${ACTUAL_OVERCOMMIT} KB"

# ------------------------------------------------------------------
# 8. Summary
# ------------------------------------------------------------------
log "===================================================="
log " OS Kernel Tuning Complete"
log "===================================================="
log ""
log "Parameters applied:"
log "  vm.nr_hugepages          = $TARGET_PAGES"
log "  vm.hugetlb_shm_group     = $EPAS_GID"
log "  vm.overcommit_memory     = 2"
log "  vm.overcommit_kbytes     = $OVERCOMMIT_KB"
log "  vm.dirty_background_ratio = 5"
log "  vm.dirty_ratio           = 10"
log "  vm.dirty_writeback_centisecs = 200"
log ""
log "Config files:"
log "  $SYSCTL_CONF"
log "  $LIMITS_CONF"
log ""

if [[ "$HP_STATUS" -ne 0 ]]; then
    log "ACTION REQUIRED: Reboot to defragment memory for HugePages."
    exit 2
fi

log "Handoff to DBA: set huge_pages = 'on' in postgresql.conf and restart EPAS."
