#!/usr/bin/env bash
#
# setup_hugepages.sh - Automate Huge Pages calculation and configuration for EPAS
# Must be executed as root (system kernel tuning required).
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Attempt to load central logger if present, else fallback to standard echo
if [ -f "${SCRIPT_DIR}/../config/logger.sh" ]; then
    source "${SCRIPT_DIR}/../config/logger.sh"
else
    log_info() { echo "[INFO] $1"; }
    log_warn() { echo "[WARN] $1"; }
    log_error() { echo "[ERROR] $1" >&2; }
    log_audit() { echo "[AUDIT] $1"; }
fi

# Default Fallback Values
ENV_FILE=""
EPAS_USER="enterprisedb"
EPAS_SERVICE="edb-as-17"
SYSCTL_CONF="/etc/sysctl.d/99-epas-hugepages.conf"
LIMITS_CONF="/etc/security/limits.d/99-epas.conf"
THP_SYSFS="/etc/tmpfiles.d/00-disable-thp.conf"  # not using /usr/lib/tmpfiles.d to priortize
APPLY_EPAS_CONF=false

# Parse command line flags (--env support)
while [[ $# -gt 0 ]]; do
    case "$1" in
        --env)
            ENV_FILE="$2"
            shift 2
            ;;
        --apply-epas-conf)
            APPLY_EPAS_CONF=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [--env /path/to/deploy.env] [--apply-epas-conf]"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Load environment configuration if provided (--env)
if [ -n "$ENV_FILE" ]; then
    if [ -f "$ENV_FILE" ]; then
        log_info "Loading parameters from environment file: $ENV_FILE"
        set -o allexport
        source "$ENV_FILE"
        set +o allexport

        # Alias variables from deploy.env to script defaults with safe fallbacks
        EPAS_USER="${EPAS_USER:-${SYSTEM_USER:-enterprisedb}}"
        EPAS_SERVICE="${EPAS_SERVICE:-${SERVICE_NAME:-edb-as-17}}"
        SYSCTL_CONF="${SYSCTL_CONF:-/etc/sysctl.d/99-epas-hugepages.conf}"
        LIMITS_CONF="${LIMITS_CONF:-/etc/security/limits.d/99-epas.conf}"
        THP_SYSFS="${THP_SYSFS:-/etc/tmpfiles.d/00-disable-thp.conf}"
    else
        log_error "Environment file '$ENV_FILE' not found."
        exit 1
    fi
fi

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
    log_error "This script modifies kernel settings and must be run as root or via sudo."
    exit 1
fi

log_info "===================================================="
log_info " Starting EPAS Huge Pages & THP Optimization"
log_info "===================================================="
log_info "Target User: $EPAS_USER | Target Service: $EPAS_SERVICE"

# 1. Locate Master EPAS Process
log_info "[1/6] Locating main EPAS process..."
MAIN_PID=$(pgrep -u "$EPAS_USER" -f "edb-postgres" | head -n 1 || true)

if [ -z "$MAIN_PID" ]; then
    log_error "edb-postgres process is not running for user '$EPAS_USER'."
    log_error "EPAS must be active with configured shared_buffers to calculate memory allocation."
    exit 1
fi
log_info "      Target EPAS Main PID: $MAIN_PID"

# 2. Get GID of EPAS user
log_info "[2/6] Querying $EPAS_USER user group details..."
if ! EPAS_GID=$(id -g "$EPAS_USER"); then
    log_error "OS User '$EPAS_USER' does not exist."
    exit 1
fi
log_info "      Group ID (GID) for $EPAS_USER is: $EPAS_GID"

# 3. Calculate Memory Footprint
log_info "[3/6] Analyzing shared memory allocation..."
SHARED_KB=$(pmap "$MAIN_PID" | awk '/rw-s/ && /zero/ {print $2}' | sed 's/K//' | awk '{sum+=$1} END {print sum}')

if [ -z "$SHARED_KB" ] || [ "$SHARED_KB" -eq 0 ]; then
    log_warn "Could not isolate anonymous shared memory using pmap. Attempting IPCS fallback..."
    SHARED_KB=$(ipcs -m | awk -v user="$EPAS_USER" '$3 == user {print $5/1024}' | awk '{sum+=$1} END {print sum}')
fi

if [ -z "$SHARED_KB" ] || [ "$SHARED_KB" -eq 0 ]; then
    log_error "Failed to calculate EPAS shared memory footprint."
    exit 1
fi

HP_SIZE_KB=$(grep ^Hugepagesize /proc/meminfo | awk '{print $2}')
log_info "      Detected OS HugePage size: ${HP_SIZE_KB} kB"
log_info "      Target EPAS Shared Memory requirement: ${SHARED_KB} kB"

# Calculate pages, rounding up, and adding a 10-page safety buffer
TARGET_PAGES=$(( (SHARED_KB / HP_SIZE_KB) + 1 + 10 ))
log_info "      Calculated target Huge Pages: $TARGET_PAGES"

# 4. Write OS Kernel Configurations
log_info "[4/6] Applying Kernel settings..."
cat << EOF > "$SYSCTL_CONF"
# Auto-generated by setup_hugepages.sh
vm.nr_hugepages = $TARGET_PAGES
vm.hugetlb_shm_group = $EPAS_GID
EOF
sysctl -p "$SYSCTL_CONF" >/dev/null
log_info "      Applied kernel parameters via $SYSCTL_CONF"

# 5. Set Shell Limits (POSIX Memlock)
log_info "[5/6] Writing security limits..."
cat << EOF > "$LIMITS_CONF"
# Auto-generated by setup_hugepages.sh
$EPAS_USER soft memlock unlimited
$EPAS_USER hard memlock unlimited
EOF
log_info "      Configured unrestricted memlock in $LIMITS_CONF"

# 6. Disable Transparent Huge Pages (THP)
log_info "[6/6] Disabling Transparent Huge Pages (THP)..."

# Apply dynamically in sysfs
if [ -f /sys/kernel/mm/transparent_hugepage/enabled ]; then
    echo never > /sys/kernel/mm/transparent_hugepage/enabled || true
fi
if [ -f /sys/kernel/mm/transparent_hugepage/defrag ]; then
    echo never > /sys/kernel/mm/transparent_hugepage/defrag || true
fi

# Persist across reboots using systemd tmpfiles.d
cat << EOF > "$THP_SYSFS"
# Auto-generated by setup_hugepages.sh
w /sys/kernel/mm/transparent_hugepage/enabled - - - - never
w /sys/kernel/mm/transparent_hugepage/defrag - - - - never
EOF
log_info "      Disabled THP dynamically and persisted via $THP_SYSFS"

# 7. Optional Automatic EPAS Configuration
if [ "$APPLY_EPAS_CONF" = true ]; then
    log_info "Enforcing huge_pages = 'on' in EPAS configuration..."
    sudo -u "$EPAS_USER" psql -d edb -c "ALTER SYSTEM SET huge_pages = 'on';"
    log_info "EPAS configuration updated. A service restart of $EPAS_SERVICE is required to complete."
fi

log_audit "HugePages configured ($TARGET_PAGES pages) and THP disabled for $EPAS_USER"

log_info "===================================================="
log_info " OS Configuration Complete!"
log_info "===================================================="
log_info "To finalize implementation:"
if [ "$APPLY_EPAS_CONF" = false ]; then
    log_info "1. Enforce huge pages in EPAS:"
    log_info "   sudo -u $EPAS_USER psql -c \"ALTER SYSTEM SET huge_pages = 'on';\""
fi
log_info "2. Restart the EPAS service:"
log_info "   systemctl restart $EPAS_SERVICE"
log_info "3. Verify pages are in use:"
log_info "   grep Huge /proc/meminfo"
log_info "===================================================="